[package]
name = "equinox"
version = "0.1.0"
authors = ["Thomas Bénéteau <thomas@bitwise.me>"]
description = "WebGL2 real-time path tracer"
edition = "2018"
build = "build.rs"

[dependencies.cgmath]
version = "0.17"
features = ["serde"]

[dependencies.console_error_panic_hook]
version = "0.1"

[dependencies.console_log]
version = "0.1"

[dependencies.half]
version = "1.3"

[dependencies.itertools]
version = "0.8"

[build-dependencies.lazy_static]
version = "1.4"

[build-dependencies.regex]
version = "1.3"

[dependencies.js-sys]
version = "0.3"

[dependencies.log]
version = "0.4"

[dependencies.maplit]
version = "1.0"

[dependencies.ordered-float]
version = "1.0"

[dependencies.rand]
version = "0.7"

[dependencies.rand_chacha]
version = "0.2"

[dependencies.regex]
version = "1.3"

[dependencies.quasirandom]
version = "0.2"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.smart-default]
version = "0.5"

[dependencies.wasm-bindgen]
version = "0.2"
features = ["serde-serialize"]

[dependencies.web-sys]
version = "0.3"
features = [
  'WebGlBuffer',
  'WebGl2RenderingContext',
  'WebGlProgram',
  'WebGlShader',
  'WebGlTexture',
  'WebGlQuery',
  'WebGlUniformLocation',
  'ExtDisjointTimerQuery',
  'WebGlFramebuffer',
]

[dependencies.zerocopy]
version = "0.2"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
